site_name: Eifueo
site_url: "https://eggworld.tk"
nav:
  - Home: index.md
  - Grade 11 IB:
      - SL Physics 1: g11/sph3u7.md
      - SL Physics 2: g11/sph4u7.md
      - SL Math - Analysis and Approaches 1: g11/mhf4u7.md
      - SL Math - Analysis and Approaches 2: g11/mcv4u7.md
      - HL English 1: g11/eng3uz.md
      - HL Chemistry 1: g11/sch3uz.md
      - HL History 1: g11/chw3mz.md
      - Theory of Knowledge: g11/tok.md
  - Grade 12 IB:
      - SL French 1: g12/fsf3u7.md
      - SL French 2: g12/fsf3uz.md
      - HL Chemistry 2: g12/sch4uz.md
      - HL Chemistry 3: g12/snc4mz.md
      - HL English 2: g12/eng4uz.md
      - HL History 2: g12/chy4uz.md
  - Computer Engineering 1A:
      - "ECE 105: Classical Mechanics": ce1/ece105.md
      - "ECE 150: C++": ce1/ece150.md
      - "ECE 190: What's An Engineer?": ce1/ece190.md
      - "GENE 191: Engineering English": ce1/gene191.md
      - "MATH 115: Linear Algebra": ce1/math115.md
      - "MATH 117: Calculus 1": ce1/math117.md
  - Computer Engineering 1B:
      - "ECE 106: Electricity & Magnets": ce1/ece106.md
      - "ECE 108: Discrete Math 1": ce1/ece108.md
      - "ECE 124: Digital Circuits": ce1/ece124.md
      - "ECE 140: Linear Circuits": ce1/ece140.md
      - "ECE 192: Engineering Economics": ce1/ece192.md
      - "MATH 119: Calculus 2": ce1/math119.md

theme:
  name: material

markdown_extensions:
  - mdx_math:
      add_preview: True
      enable_dollar_delimiter: True
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: True

extra_javascript:
  ["https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js", "mathjax-config.js"]
