site_name: Eifueo
site_description: "A collection of personal notes throughout school"
site_author: "Daniel Chen"
copyright: "Text licensed under the GNU Free Documentation License"
site_url: "https://eifueo.eggworld.me"
repo_url: "https://git.eggworld.me/eggy/eifueo"
repo_name: Gitea
nav:
  - Home: index.md
  - Grade 11 IB:
      - SL Physics 1: g11/sph3u7.md
      - SL Physics 2: g11/sph4u7.md
      - SL Math - Analysis and Approaches 1: g11/mhf4u7.md
      - SL Math - Analysis and Approaches 2: g11/mcv4u7.md
      - SL French 1: g11/fsf3u7.md
      - HL English 1: g11/eng3uz.md
      - HL Chemistry 1: g11/sch3uz.md
      - HL History 1: g11/chw3mz.md
      - Theory of Knowledge: g11/tok.md
  - Grade 12 IB:
      - SL French 2: g12/fsf3uz.md
      - HL Chemistry 2: g12/sch4uz.md
      - HL Chemistry 3: g12/snc4mz.md
      - HL English 2: g12/eng4uz.md
      - HL History 2: g12/chy4uz.md
  - Computer Engineering 1A:
      - "ECE 105: Classical Mechanics": 1a/ece105.md
      - "ECE 150: C++": 1a/ece150.md
      - "MATH 115: Linear Algebra": 1a/math115.md
      - "MATH 117: Calculus 1": 1a/math117.md
  - Computer Engineering 1B:
      - "ECE 106: Electricity & Magnets": 1b/ece106.md
      - "ECE 108: Discrete Math 1": 1b/ece108.md
      - "ECE 124: Digital Circuits": 1b/ece124.md
      - "ECE 140: Linear Circuits": 1b/ece140.md
      - "ECE 192: Engineering Economics": 1b/ece192.md
      - "MATH 119: Calculus 2": 1b/math119.md
  - Computer Engineering 2A:
      - "ECE 109: Materials Chemistry": 2a/ece109.md
      - "ECE 240: Electronic Circuits": 2a/ece240.md
      - "ECE 222: Digital Computers": 2a/ece222.md
      - "ECE 250: DSA": 2a/ece250.md
      - "ECE 205: Advanced Calculus 1": 2a/ece205.md
      - "ECE 204: Numerical Methods": 2a/ece204.md
  - Computer Engineering 2B:
      - "ECE 208: Discrete Math 2": 2b/ece208.md
      - "ECE 207: Signals": 2b/ece207.md
      - "BIOL 240: Microbiology 1": 2b/biol240.md
      - "ECE 203: Probability": 2b/ece203.md
      - "ECE 224: Embedded": 2b/ece224.md
      - "ECE 252: Concurrency": 2b/ece252.md

theme:
  name: material

markdown_extensions:
  - mdx_math:
      enable_dollar_delimiter: True
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - def_list
  - footnotes
  - toc:
      permalink: True

extra_javascript:
  [
    "https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.2/katex.min.js",
    "https://cdn.jsdelivr.net/npm/katex@0.16.2/dist/contrib/mhchem.min.js",
    "https://cdn.jsdelivr.net/npm/katex/dist/contrib/mathtex-script-type.min.js",
  ]

extra_css:
  ["https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.2/katex.min.css", "fix_katex.css"]
