site_name: Eifueo
nav:
  - Home: index.md
  - SL Physics 1: sph3u7.md
  - SL Physics 2: sph4u7.md
  - SL Math - Analysis and Approaches 1: mhf4u7.md
  - SL Math - Analysis and Approaches 2: mcv4u7.md
  - SL French 1: fsf3u7.md
  - HL Chemistry 1: sch3uz.md
  - HL English 1: eng3uz.md
  - HL History 1: chw3mz.md
  - Theory of Knowledge: tok.md

theme:
  name: material

markdown_extensions:
  - mdx_math:
      add_preview: True
      enable_dollar_delimiter: True
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript: [
  'https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js',
  'mathjax-config.js'
]
