site_name: Eifueo
nav:
  - Home: index.md
  - SL Physics A: sph3u7.md
  - HL Chemistry A: sch3uz.md
  - SL Math - Analysis and Approaches A: mhf4u7.md
  - HL English A: eng3uz.md
  - IB Resources: resources.md

theme:
  name: material

markdown_extensions:
  - mdx_math:
      add_preview: True
      enable_dollar_delimiter: True
  - admonition
  - pymdownx.details
  - pymdownx.superfences

#extra_css: [
#  'https://cdn.jsdelivr.net/npm/katex/dist/katex.min.css'
#]

extra_javascript: [
#  'https://cdn.jsdelivr.net/npm/katex/dist/katex.min.js',
#  'https://cdn.jsdelivr.net/npm/katex/dist/contrib/mathtex-script-type.min.js'
#]
  'https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js',
  'mathjax-config.js'
]
