site_name: Eifueo
nav:
  - Home: index.md
  - SL Physics A: sph3u7.md
  - HL Chemistry A: sch3uz.md
  - SL Math - Analysis and Approaches A: mhf4u7.md
  - HL English A: eng3uz.md

theme:
  name: material

markdown_extensions:
  - mdx_math:
      add_preview: True
      enable_dollar_delimiter: True
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript: [
  'https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js',
  'mathjax-config.js'
]
